global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'
    region: 'local'

# Правила алертов
rule_files:
  - "rules.yml"

# Настройка AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Сбор метрик
scrape_configs:
  # Сам Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Orders API
  - job_name: 'orders-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['orders-api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'orders-api'

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']